name: Convert TSV Files

on:
  push:
    branches:
      - main  # Trigger the action on a push to the `main` branch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install pandas

      # Step 4: Run the conversion script (your Python script that converts TSV to JSON, CSV, etc.)
      - name: Convert TSV to JSON, CSV, TSV, and XML
        run: python conversion.py

      # Step 5: Commit only the new files (folders and converted files) to a new branch
      - name: Commit converted files
        env:
          OUTPUT_BRANCH: "v0.3"  # Set your preferred branch name
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create and switch to the new branch
          git checkout -b "$OUTPUT_BRANCH"
          
          # Clean the repository, removing all existing files except the newly created folders
          git rm -rf .  # Remove all files from the repository
          
          # Re-add the newly created directories and files
          git add json/ csv/ tsv/ xml/
          
          # Commit the changes
          git commit -m "Auto-converted TSV files"
          
          # Push the new branch to the repository (force push to overwrite the branch)
          git push origin "$OUTPUT_BRANCH" --force
