name: Convert Files and Create New Branch

on:
  push:
    branches:
      - main

jobs:
  convert_and_create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas  # Add any other dependencies you need

      - name: Run conversion script
        run: |
          python conversion.py  # Ensure this is the script you want to run

      - name: Create new branch for output
        run: |
          NEW_BRANCH="v0.3"  # This is the new branch name
          git checkout --orphan $NEW_BRANCH  # Create a new branch without any history
          git reset --hard  # Reset working tree to remove all files

      - name: Create required folders and README
        run: |
          # Create required folders
          mkdir json csv tsv xml
          
          # Create a README file
          echo "# Converted Files" > README.md
          echo "This branch contains the converted files (JSON, CSV, TSV, XML)." >> README.md

      - name: Add new files to git
        run: |
          git add .
          git commit -m "Add converted files and folders"

      - name: Push new branch to GitHub
        run: |
          git push origin $NEW_BRANCH  # Push the newly created branch with the folders and README
